apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-stock-api
  namespace: jenkins
  labels:
    app: jenkins-stock-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins-stock-api
  template:
    metadata:
      labels:
        app: jenkins-stock-api
    spec:
      containers:
      - name: jenkins-stock-api
        image: jenkins-stock-api:v2
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-stock-api
  namespace: jenkins
spec:
  selector:
    app: jenkins-stock-api
  ports:
    - name: http
      port: 8000
      targetPort: 8000
